FROM nginx

WORKDIR /etc/nginx
COPY ./nginx.conf .

WORKDIR /usr/share/nginx/html/book
COPY ./dist/book .

WORKDIR /usr/share/nginx/html/life
COPY ./dist/life .

WORKDIR /usr/share/nginx/html/system
COPY ./dist/system .

RUN ls

CMD ["cd /usr/share/nginx/html/system", "npm install", "npm run start"]

EXPOSE 80