name: Docker Image CI

on:
  push:
    branches: [ dev ]

jobs:

  build:
    name: build docker image & push hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: npm i
           npm run dev
           
