name: Build a sufu.site Image AND Push Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: 获取主库源码
        uses: actions/checkout@v2

      # - name: 安装 tree
      #   run: sudo apt install tree

      - name: 登陆 docker 账户
        uses: docker/login-action@v1
        with:
          username: sufuwang
          password: ${{ secrets.DockerPassWord }}

      - name: 获取 dist 仓库
        uses: actions/checkout@v2
        with:
          ref: master
          repository: sufuwang/dist.sufu.site
          token: ${{ secrets.SubmoduleToken }}
          path: ./dist

      - name: 执行脚本
        run: yarn build

      - name: 更新远端镜像
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSHHost }}
          port: 22
          username: ubuntu
          key: ${{ secrets.SSHPrivateKey }}
          script: |
            sudo chmod 666 /var/run/docker.sock
            docker login -u sufuwang --password-stdin ${{ secrets.DockerPassWord }}
            docker rm sufu.site.nginx -f
            docker rm sufu.site.nodejs -f
            docker rmi sufuwang/sufu_site_nginx
            docker rmi sufuwang/sufu_site_nodejs
            docker pull sufuwang/sufu_site_nginx
            docker pull sufuwang/sufu_site_nodejs
            docker run -d -p 80:80 --name sufu.site.nginx sufuwang/sufu_site_nginx
            docker run -d -h 0.0.0.0 -p 4002:4002 --name sufu.site.nodejs sufuwang/sufu_site_nodejs