name: Build a sufu.site Image AND Push Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: 获取主库源码
        uses: actions/checkout@v2

      # - name: 安装 tree
      #   run: sudo apt install tree

      - name: 登陆 docker 账户
        uses: docker/login-action@v1
        with:
          username: sufuwang
          password: ${{ secrets.DockerPassWord }}

      - name: 获取 book 源码
        uses: actions/checkout@v2
        with:
          repository: sufuwang/book.sufu.site
          token: ${{ secrets.SubmoduleToken }}
          path: ./book
      
      - name: 获取 life 源码
        uses: actions/checkout@v2
        with:
          repository: sufuwang/life.sufu.site
          token: ${{ secrets.SubmoduleToken }}
          path: ./life

      - name: 执行脚本
        env:
          imageName: sufuwang/sufu.site
          containerName: sufu.site.nginx
        run: yarn run workflow:dev

      - name: 更新远端镜像
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSHHost }}
          port: 22
          username: ubuntu
          password: ${{ secrets.SSHPassWord }}
          script: |
            sudo chmod 666 /var/run/docker.sock
            docker rm sufu.site.nginx -f
            docker rmi sufuwang/sufu.site
            docker pull sufuwang/sufu.site
            docker run -d -p 80:80 --name sufu.site.nginx sufuwang/sufu.site
